<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 */

/**
 * User: Alex Gusev <alex@flancer64.com>
 */
class Praxigento_Bonus_Factory extends Nmmlm_Core_Factory
{

    /**
     * Return project specific connector to backend (OpenERP or other).
     *
     * @return \Nmmlm_Core_Datasource_Backend_Connector_Interface
     */
    public function getBackendConnector()
    {
        if (is_null(self::$_backendConnector)) {
            self::$_backendConnector = Mage::getModel('prxgt_bonus_model/own_backend_connector');
        }
        return self::$_backendConnector;
    }

    public function getReferralCustomerProcessor()
    {
        return parent::getReferralCustomerProcessor(); // TODO: Change the autogenerated stub
    }
}