<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 *
 * User: Alex Gusev <alex@flancer64.com>
 */
?>
<?php
use Praxigento_Bonus_Block_Adminhtml_Own_Customer_Downline_Validation_Index as BLOCK;

/** @var  $this Praxigento_Bonus_Block_Adminhtml_Own_Customer_Downline_Validation_Index */
$periods = $this->getPeriodsAvailable();
?>
<div align="center">
    <h1><?php $this->uiTitle() ?></h1>
</div>

<?php $this->uiScriptFormSubmit() ?>

<div class="prxgtFormLayout">
    <form method="post" action="<?php echo $this->getUrl('*/*/result'); ?>" id="<?php $this->uiDomForm() ?>">
        <input name="form_key" type="hidden" value="<?php $this->uiFormKey() ?>"/>

        <?php if(sizeof($periods) == 0): ?>

            <div class="prxgtRow">
                <?php $this->ui('There are no periods with downline snapshots.') ?>
            </div>

        <?php else: ?>

            <div class="prxgtRow">
                <div class="prxgtRowLabel">
                    <?php $this->ui('Available periods:') ?>
                </div>
                <div class="prxgtRowValue">
                    <select id="<?php echo BLOCK::DOM_SELECT ?>" name="<?php echo BLOCK::DOM_SELECT ?>">
                        <?php foreach($periods as $one): ?>
                            <option><?php echo $one[ Praxigento_Bonus_Model_Own_Snap_Downline::ATTR_PERIOD ] ?></option>
                        <?php endforeach ?>
                    </select>
                </div>
                <div class="clear"></div>
            </div>

            <div class="prxgtRow">
                <?php $this->ui('Select period then press \'OK\' to validate downline tree.') ?>
            </div>

            <div class="prxgtRow">
                <div class="prxgtBtn">
                    <?php $this->uiButtonSubmit(' OK ') ?>
                </div>
                <div class="clear"></div>
            </div>

        <?php endif ?>

    </form>
</div>
