<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 *
 * User: Alex Gusev <alex@flancer64.com>
 */
?>
<?php
/** @var  $this Nmmlm_Core_Block_Adminhtml_Own_Customer_Tree_Validation_Preview */
/** @var  $entries Nmmlm_Core_Model_Own_Service_Tree_Validation_Bean_ErrorEntry[] */
$entries = $this->getInvalidEntries();
?>
<div align="center">
    <h1><?php $this->uiTitle() ?></h1>
</div>

<?php $this->uiScriptFormSubmit() ?>

<div class="nmmlmFormLayout">
    <form method="post" action="<?php echo $this->getUrl('*/*/result'); ?>" id="<?php $this->uiDomForm() ?>">
        <input name="form_key" type="hidden" value="<?php $this->uiFormKey() ?>"/>

        <?php if(sizeof($entries)): ?>


            <div class="nmmlmRow">
                <?php $this->ui('There are validation errors.') ?>
            </div>

            <table>
                <tr>
                    <th><?php $this->ui('ID') ?></th>
                    <th><?php $this->ui('Actual Path') ?></th>
                    <th><?php $this->ui('Expected Path') ?></th>
                </tr>
                <?php foreach($entries as $one): ?>
                    <tr>
                        <td><?php echo $one->getCustomerIdMlm() ?></td>
                        <td><?php echo $one->getPathActual() ?></td>
                        <td><?php echo $one->getPathExpected() ?></td>
                    </tr>
                <?php endforeach ?>
            </table>

            <div class="nmmlmRow">
                <?php $this->ui('Press \'Fix\' button to fix customer tree integrity.') ?>
            </div>

            <div class="nmmlmRow">
                <div class="nmmlmBtn">
                    <?php $this->uiButtonSubmit(' Fix ') ?>
                </div>
                <div class="clear"></div>
            </div>


        <?php else: ?>


            <div class="nmmlmRow">
                <?php $this->ui('There are no validation errors.') ?>
            </div>


        <?php endif ?>


    </form>
</div>
