<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 */

/**
 * User: Alex Gusev <alex@flancer64.com>
 *
 * @method int getPayoutId()
 * @method null setPayoutId(int $val)
 * @method int getTransactId()
 * @method null setTransactId(int $val)
 */
class Praxigento_Bonus_Model_Own_Payout_Transact extends Mage_Core_Model_Abstract
{
    const ATTR_PAYOUT_ID = 'payout_id';
    const ATTR_TRANSACT_ID = 'transact_id';

    public function getId()
    {
        return parent::getId(); // TODO: Change the autogenerated stub
    }

    public function getIdFieldName()
    {
        return parent::getIdFieldName(); // TODO: Change the autogenerated stub
    }

    public function getEntityId()
    {
        return parent::getEntityId(); // TODO: Change the autogenerated stub
    }


}