<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 */

/**
 * User: Alex Gusev <alex@flancer64.com>
 *
 * @method string getFormTitle()
 * @method null setFormTitle(string $value)
 */
class Praxigento_Bonus_Block_Adminhtml_Own_Customer_Downline_Validation_Index
    extends Praxigento_Bonus_Block_Adminhtml_Own_Base {

    public function uiTitle() {
        echo $this->__('Customer Tree Validation');
    }

    public function getPeriodsAvailable() {
    }

    /**
     * Initialize factory instance
     *
     * @param array $args
     */
    public function __construct(array $args = array()) {
        parent::__construct($args); // TODO: Change the autogenerated stub
    }
}