<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 */

/**
 * User: Alex Gusev <alex@flancer64.com>
 */
/** @var $this Praxigento_Bonus_Block_Adminhtml_Own_Sales_Bonus_Collect_Transact_Post */
?>

<h2 align="center"><?php $this->ui('Collect Bonus Transactions') ?></h2>

<div class="nmmlmFormLayout">


    <?php if ($this->isRetailBonusEnabled()): ?>


        <div class="nmmlmRow">
            <?php $this->ui('Total %s transactions are collected.', $this->getCollectedCount()) ?>
        </div>


    <?php else: ?>


        <div class="nmmlmRow">
            <?php $this->ui('Bonus is disabled.') ?>
        </div>


    <?php endif; ?>

</div>