<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 */

/**
 * User: Alex Gusev <alex@flancer64.com>
 */
/** @var $this Praxigento_Bonus_Block_Adminhtml_Own_Sales_Bonus_Process_Pv_Post */
?>

<h2 align="center"><?php $this->ui('Personal Volume Bonus') ?></h2>

<div class="nmmlmFormLayout">


    <?php if ($this->isPersonalBonusEnabled()): ?>

        <?php if ($this->getIsCalculationDone()): ?>
            <div class="nmmlmRow">Done successfully.</div>
        <?php else: ?>
            <div class="nmmlmRow">Calculation is failed.</div>
        <?php endif; ?>

    <?php else: ?>


        <div class="nmmlmRow">
            <?php $this->ui('Personal Volume Bonus is disabled.') ?>
        </div>


    <?php endif; ?>

</div>