<?php
/**
 * Copyright (c) 2015, Praxigento
 * All rights reserved.
 */

/**
 * User: Alex Gusev <alex@flancer64.com>
 */
/** @var $this Praxigento_Bonus_Block_Adminhtml_Own_Sales_Bonus_Collect_Retail_Post */
?>
<style>
    .nmmlmFormLayout {
        margin: 0 auto;
        width: 400px;
    }
</style>


<h2 align="center"><?php $this->ui('Process Retail Bonus') ?></h2>

<div class="nmmlmFormLayout">


    <?php if ($this->isRetailBonusEnabled()): ?>


        <div class="nmmlmRow">
            <?php $this->ui('Total %s orders are processed.', $this->getProcessedCount()) ?>
        </div>

        <?php $failed = $this->getFailedOrders(); ?>

        <?php if (count($failed)) : ?>
            <div class="nmmlmRow">
                <pre>
                    <?php
                    foreach ($failed as $id => $msg) {
                        echo "\n$id:\t$msg";
                    }
                    ?>
                </pre>
            </div>
        <?php endif; ?>

    <?php else: ?>


        <div class="nmmlmRow">
            <?php $this->ui('Retail bonus is disabled.') ?>
        </div>


    <?php endif; ?>

</div>